language: csharp
dist: trusty
sudo: true

os:
  - linux
  - osx

mono:
  - nightly
  - latest
  - 5.10.0
  - 5.8.0

install:

script: ./mono/build-mono.sh && ./mono/test-mono.sh

#  allow_failures:
#    - os: osx
#      mono: latest
