os: Visual Studio 2017

init:
  - git config --global core.autocrlf input

build_script: 
  - cmd: dotnet --info
  - cmd: build.bat
  - ps: .\mono\appveyor.ps1

test: off
version: '{build}'
artifacts:
  - path: release
  - path: release\*.nupkg
